import { generateText } from "ai";
import { google } from "@ai-sdk/google";
import { NextResponse } from "next/server";

// Simple in-memory cache (you can replace with Redis, Vercel KV, or database)
const cache = new Map<string, string>();

export async function POST(req: Request) {
  try {
    const { prompt } = await req.json();

    // Check cache first
    if (cache.has(prompt)) {
      return NextResponse.json({ 
        text: cache.get(prompt), 
        source: "cache" 
      });
    }

    let text = "";
    let source = "";

    // --- 1️⃣ Primary: Gemini ---
    if (process.env.GOOGLE_GENERATIVE_AI_API_KEY) {
      try {
        const geminiResp = await generateText({
          model: google("models/gemini-2.0-flash-exp"),
          prompt,
        });
        text = geminiResp.text;
        source = "gemini";
      } catch (geminiError: any) {
        console.warn("Gemini API failed:", geminiError.message);
      }
    } else {
      console.warn("Gemini key missing. Skipping Gemini.");
    }

    // --- 2️⃣ Secondary: Hugging Face fallback ---
    if (!text) {
      const hfKey = process.env.HF_API_KEY;
      if (!hfKey) throw new Error("HF_API_KEY missing. Cannot use Hugging Face fallback.");

      const hfResponse = await fetch(
        "https://router.huggingface.co/hf-inference/tiiuae/falcon-7b-instruct",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${hfKey}`,
          },
          body: JSON.stringify({ inputs: prompt }),
        }
      );

      if (!hfResponse.ok) {
        const errText = await hfResponse.text();
        throw new Error(`Hugging Face API error: ${errText}`);
      }

      const hfData = await hfResponse.json();
      text = Array.isArray(hfData)
        ? hfData[0]?.generated_text || ""
        : hfData.generated_text || "";

      source = "huggingface";
    }

    if (!text) throw new Error("No text generated by any AI.");

    // Save to cache
    cache.set(prompt, text);

    return NextResponse.json({ text, source });

  } catch (error: any) {
    console.error("All AI attempts failed:", error.message);
    return NextResponse.json(
      { error: true, details: error.message },
      { status: 500 }
    );
  }
}
